### ISSUE TITLE
Questions about datastructure.py

### ISSUE THREAD

**Issue by JiseungHong** [qbhan/CS420#6]
In datastructure.py...

1. Why does "class Array" have an attribute "value"?
"class Array" is defined to represent statement such as "int A[10]". Then each attributes become "self.type == int, self.name = A, self.length = 10". Then why is the attribute "value" needed?

2. What is the difference between "class For" and "class ForStmt"? (In same way, what is the difference btw "class If" and "class IfStmt"?

**Comment by qbhan** [comment]
1. Class 'Array' is made roughly. I'll adjust it when adding a class for assignment.

2. They are the same. ForStmt and IfStmt are made by me before implementing their grammar made by WooChang Jung. When I merged his code to datastructure.py, I missed erasing the previous class. I make sure to erase it.

**Comment by JiseungHong** [comment]
💯
